version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: nestjs_backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - '27022:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports: 
    - "3020:80"
    tty: true
    stdin_open: true
    restart: on-failure
    depends_on: 
     - backend
volumes:
  mongo_data: