version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: nestjs_app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - '27022:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: