name: Deploy project

on:
  push:
    branches:
      - main  # Запускать workflow только при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Копирование файлов на сервер через SSH
      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/var/www/myapp"  # Папка на сервере, куда будут скопированы файлы

      # Шаг 3: Запуск Docker Compose на сервере через SSH
      - name: Run Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/myapp
            docker-compose down  # Останавливаем и удаляем старые контейнеры
            docker-compose up -d  # Запускаем новые контейнеры в фоновом режиме